#!/usr/bin/perl -w
#print referer from a httpd access log 
use weblog;
use Getopt::Std;
our($opt_n);
our($opt_u);
getopts('nu') or die "unknown option\n";

while (<>) { 
	my ($req, $ref, $client, $ip);
	weblog::parse_weblog();
	next unless defined($weblog::referer);
	$ref = $weblog::referer;
	next if $ref eq "-";
	#next if $ref =~ /www\.google\..*\/search.*q=/;
	#next if $ref =~ /search\.msn\.com.*q=/;
	#next if $ref =~ /search\.live\.com.*q=/;
	#next if $ref =~ /search\.yahoo\..*\/search/;
	#next if $ref =~ /www\.ask\.com\/web/;
	#next if $ref =~ /www\.BigFinder\.de/;
	if ($opt_n) { 
		printf "%-18s ", $weblog::ip;
	}
	if ($opt_u) { 
		my ($cmd, $url, $http) = split(/ /, $weblog::req);
		printf("%-20s ", $url);
	}
	print $ref,"\n";
}
