#!/usr/bin/perl -w
#print referer from a httpd access log 

use Getopt::Std;
our($opt_n);
our($opt_a);
our($opt_u);
getopts('nau') or die "unknown option\n";

while (<>) { 
	my ($req, $ref, $client, $ip);
	($req, $ref, $client) = /"([^"]*)" \S+ \S+ "([^"]*)" "([^"]*)"/;
	next unless defined($ref);
	next if $ref eq "-";
	#next if $ref =~ /www\.google\..*\/search.*q=/;
	#next if $ref =~ /search\.msn\.com.*q=/;
	#next if $ref =~ /search\.live\.com.*q=/;
	#next if $ref =~ /search\.yahoo\..*\/search/;
	#next if $ref =~ /www\.ask\.com\/web/;
	#next if $ref =~ /www\.BigFinder\.de/;
	if ($opt_n) { 
		($ip) = /(\d+\.\d+\.\d+\.\d+)/;
		printf "%-18s ", $ip;
	}
	if ($opt_u) { 
		my ($cmd, $url, $http) = split(/ /, $req);
		printf("%-20s ", $url);
	}
	printf("%-20s ", $client) if $opt_a;
	print $ref,"\n";
}
