#!/usr/bin/perl -n -w
# display search engines
use FindBin qw($Bin);
use lib "$Bin";
use weblog;

weblog::parse_weblog();
next unless ($weblog::req =~ /robots\.txt/);
if ($weblog::useragent eq "-") { 
	print "$weblog::referer\n";
} else { 
	weblog::clean_useragent();
	print "$weblog::useragent\n";
}

