#!/usr/bin/perl -n -w
# display search engines
use weblog;

weblog::parse_weblog();
next unless ($weblog::req =~ /robots\.txt/);
if ($weblog::useragent eq "-") { 
	print "$weblog::referer\n";
} else { 
	print "$weblog::useragent\n";
}

