#!/usr/bin/perl -w
use weblog;

%hits = ();

while (<>) { 
	weblog::parse_weblog();
	my ($cmd, $url, $http) = split(/ /, $weblog::req);
	$hits{$url}++;
}

foreach $i (sort { $hits{$b} <=> $hits{$a} } keys %hits) { 
	printf "%7d %s\n", $hits{$i}, $i;
}
