#!/usr/bin/perl -w
# print hits for pages
use FindBin qw($Bin);
use lib "$Bin";
use weblog;

%hits = ();

while (<>) { 
	weblog::parse_weblog();
	my ($cmd, $url, $http) = split(/ /, $weblog::req);
	$hits{$url}++ if defined $url;
}

foreach $i (sort { $hits{$b} <=> $hits{$a} } keys %hits) { 
	printf "%7d %s\n", $hits{$i}, $i;
}
