#!/usr/bin/perl  
# TBD do useful analysis
# TBD fix -w

use weblog;

while (<>) { 
	weblog::parse_weblog();

	$ips{$weblog::ip}++;
	$ua{$weblog::ip} = $weblog::useragent;	# xxx append

	($url) = ($weblog::req =~ /GET (\S+)/);
	$urls{$url}++;
} 

# print "IPs:\n";
foreach $ip (keys(%ips)) { 
	printf "%5d $ip $ua\n", $ips{$ip};
} 


