#!/usr/bin/perl   -w
# XXX track time, filter multiple hits on pdf
use FindBin qw($Bin);
use lib "$Bin";
use weblog;
use Date::Parse;

%visitors = ();
%first = ();
%last = ();

while (<>) { 
	weblog::parse_weblog();
	weblog::clean_useragent();

	$v = $weblog::ip . " " . $weblog::useragent;
	#($url) = ($weblog::req =~ /\S+ (\S+)/);

	unless (defined($first{$v})) {
		$first{$v} = $weblog::date;
	}

	$visitors{$v}++;
	$last{$v} =  $weblog::date;
} 

foreach $v (keys(%visitors)) { 
	printf "%7d $v %ds\n", $visitors{$v}, 
		str2time($last{$v}) - str2time($first{$v});
} 


