#!/usr/bin/perl   -w
# XXX track time, filter multiple hits on pdf
use FindBin qw($Bin);
use lib "$Bin";
use weblog;

%visitors = ();

while (<>) { 
	weblog::parse_weblog();
	weblog::clean_useragent();

	$v = $weblog::ip . " " . $weblog::useragent;
	#($url) = ($weblog::req =~ /\S+ (\S+)/);

	$visitors{$v}++;
} 

foreach $v (keys(%visitors)) { 
	printf "%7d $v\n", $visitors{$v};
} 


