#!/usr/bin/perl -w
# print user agents from a log
use FindBin qw($Bin);
use lib "$Bin";
use weblog;
use Getopt::Std;
our($opt_n);
getopts('n') or die "unknown option\n";

while (<>) { 
	weblog::parse_weblog();
	weblog::clean_useragent();
	printf "%15s ", $weblog::ip if $opt_n;
	print $weblog::useragent,"\n";
}

