#!/bin/sh
# run all analyses
# TBD dns domain statistics
# time statistics
# rewrite it all into a single pass?

N=${N:-10}

for i in "$@" ; do
	echo "Analysis of $(basename $i)"
	echo
	printf "%23s" "Time: "
	webtimerange $i 
	printf "%23s" "Hits total: "
	tophits $i | awk ' { n += $1 } ; END { print n }'
	printf "%23s" "Visitor hits total: "
	removecrawl $i | tophits | awk ' { n += $1 } ; END { print n }'
	printf "%23s" "Visitors: "
	removecrawl $i | trail | wc -l 
	printf "%23s" "Bytes delivered total: "
	webbytes $i
	echo
	echo "Hits:"
	tophits $i | head -$N
	echo
	echo "Referer: "
	referer $i  | sort | uniq -c | sort -rn | head -$N
	echo
	echo "Longest visitors:"
	removecrawl $i | trail | sort -rn | head -$N | webresolveip
	echo
	echo "Errors:"
	weberrors $i | sort | uniq -c | sort -rn | head -$N
	echo 
	echo "Robots:"
	robots $i | sort | uniq -c | sort -rn | head -$N
	echo
	echo "User agents:"
	useragents $i | sort | uniq -c | sort -rn | head -$N
	echo
	echo "Search engine domains:"
	searchterms -c $i | awk ' { print $1 }' | sort | uniq -c | sort -rn | head -$N
	echo
	echo "Search engine targets:"
	searchterms -u $i | awk ' { print $1 }' | sort | uniq -c | sort -rn | head -$N
	echo
	echo "Searchterms:"
	searchterms $i | sort | uniq -c | sort -rn
done
