#!/usr/bin/perl -n  -w
# print errors from a weblog
# xxx sumarize
use FindBin qw($Bin);
use lib "$Bin";
use weblog;

weblog::parse_weblog();
if ($weblog::status < 200 || $weblog::status > 399) {
	$weblog::req =~ s/\s+HTTP\/\d+\.\d+$//;
	print "$weblog::req $weblog::status\n"
}
