#!/usr/bin/perl -w 
use FindBin qw($Bin);
use lib "$Bin";
use weblog;

$_ = <>;
weblog::parse_weblog();
$first = $weblog::date;

while (<>) {
	$n = $_;
}

$_ = $n;
weblog::parse_weblog();
print "$first - $weblog::date\n";
